compilerType=tbasic
compilers=tbasic
defaultCompiler=tbasic
supportsRustHirView=true
supportsBinary=true
supportsExecute=true
objdumper=objdump

compiler.tbasic.exe=/usr/local/bin/tbasic
compiler.tbasic.name=tbasic 1.0
